name: metrics_servicerepository
on:
  # push:
  #   branches:
  #     - prod
  # schedule:
  #   - cron: "0 1,7,13,19 * * *"
  workflow_dispatch:

jobs:
  github-actions-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics
        # uses: lowlighter/metrics@latest
        # uses: lowlighter/metrics@master
        uses: gh-metrics/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics_servicerepository.svg
          user: servicerepository
          base: header, activity, repositories, metadata
          base_indepth: yes
          config_timezone: Canada/Eastern
          config_twemoji: yes
          # config_order: base.header, base.activity+community, base.repositories, isocalendar, achievements, languages
          config_order: base.header, base.activity+community, base.repositories, achievements, languages
          # config_order: base.header, base.activity+community, base.repositories, isocalendar, achievements
          # config_order: base.header, base.activity+community, base.repositories, isocalendar, languages
          # config_order: base.header, base.activity+community, base.repositories, isocalendar
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          # plugin_isocalendar: yes
          # plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 30
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          use_prebuilt_image: yes
